name: Deploy Flask App
on:
  workflow_dispatch:
jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'sucess'
    env:
        DOCKERHUB_USER : ${{ vars.DOCKERHUB_USER }}
        DOCKER_TAG: ${{github.event.workflow_run.head_sha}}
    runs-on: self-hosted

    steps:
        - name: checkout code
          uses: actions/checkout@v4
    
        - name: deploy with docker compose
          run: docker compose up -d --build
