name: Deploy Flask App
on:
    workflow_dispatch:
jobs:
    env:
        DOCKERHUB_USER: {{vars.DOCKERHUB_USER}}
    deploy:
        runs-on: self-hosted

    steps:
       - name: checkout code
         usage: actions/checkout@v4

       - name: deploy with docker compose
         run: docker compose up -d --build
         
         
