name: DevSecOps End to End Pipeline

on:
    workflow_dispatch:

jobs:
    code-quality:
        uses: ./.github/workflows/codequality.yml

    secrets-scan:
        uses: ./.github/workflows/secret-scan.yml        

    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml        

    docker-scan:
        uses: ./.github/workflows/docker-lint.yml          