name: DevSecOps End to End Pipeline

on:
    push:
        branches: [main]

jobs:
    code-quality:
        uses: ./.github/workflows/codequality.yml

    secrets-scan:
        uses: ./.github/workflows/secret-scan.yml        

    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml        

    docker-scan:
        uses: ./.github/workflows/docker-lint.yml 

    build:
        needs: [code-quality,secrets-scan,dependency-scan,docker-scan]          
        uses: ./.github/workflows/docker-build-push.yml
        secrets: inherit
    
    trivy:
        needs: [build]
        uses: ./.github/workflows/image-scan.yml
        secrets: inherit
    
    deploy:
        needs: [build,trivy]
        uses: ./.github/workflows/deploy-to-server.yml
        secrets: inherit