name: Image Scanner

on:
    workflow_call:

jobs:

    image-scanning:
        runs-on: ubuntu-latest

        steps:
            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{vars.DOCKERHUB_USER}}
                  password: ${{secrets.DOCKERHUB_TOKEN}}

            - name: Trivy Image Scan
              uses: aquasecurity/trivy-actions@0.33.1
              with:
                severity: 'CRITICAL'
        